### PR TITLE
Very basic ItemPage styling

### PR DESCRIPTION
**Pull request by alexbnewman**

### CODE REVIEW

**Review by elaverty0103 — APPROVED** [review]
reviewed during the meeting, looks good

**Review by jennweir — APPROVED** [review]
We reviewed this code in the Sunday meeting. You cannot scan it with the QR code because we resolved the conflict and changed the ItemPage rendering back to Authenticate component.

**Comment by santiagomed** [comment]
> You cannot scan it with the QR code because we resolved the conflict and changed the ItemPage rendering back to Authenticate component.

Can you add some sort of button in each item that navigates to the corresponding ItemPage

**Comment by santiagomed** [comment]
I saw images were added as assets for the ItemPage. I am a bit hesitant to work with images because of the different screen sizes. I can't think of a different alternative so we'll have to wait and see how it plays out ig.

**Review by santiagomed — APPROVED** [review]

**Pull request merged**
